import { afterAll, beforeAll, describe, test } from "bun:test";
import { createTsfga, type RelationConfig } from "@tsfga/core";
import type { DB } from "@tsfga/kysely";
import { KyselyTupleStore } from "@tsfga/kysely";
import type { Kysely } from "kysely";
import {
  expectConfigsMatchModel,
  type FixtureRecord,
  recordFixture,
} from "./helpers/conformance.ts";
import {
  beginTransaction,
  destroyDb,
  getDb,
  rollbackTransaction,
} from "./helpers/db.ts";
import {
  type Corpus,
  cfg,
  ids,
  loadCorpus,
  runStages,
  type Stage,
} from "./matrix-corpus.ts";

/**
 * B1 tuple-to-userset corpus — parents, conditions, algebra.
 *
 * A port of upstream's own case matrix —
 * `tests/check/check_ttu.go` at v1.18.2 — over the stages
 * listed below. Every `expected` is the `Expectation:` the Go
 * corpus states, so a shape both engines answer the same
 * *wrong* way still fails.
 *
 * Stages ported here:
 * - `direct_pa_direct_ch`
 * - `or_comp_from_direct_parent`
 * - `and_comp_from_direct_parent`
 * - `butnot_comp_from_direct_parent`
 * - `userset_pa_userset_ch`
 * - `userset_pa_userset_comp_ch`
 * - `userset_pa_userset_comp_cond_ch`
 * - `userset_pa_userset_comp_wild_ch`
 * - `userset_pa_userset_comp_wild_cond_ch`
 * - `userset_cond_userset_ch`
 * - `userset_cond_userset_comp_ch`
 * - `userset_cond_userset_comp_cond_ch`
 * - `userset_cond_userset_comp_wild_ch`
 * - `userset_cond_userset_comp_wild_cond_ch`
 * - `or_ttu`
 * - `and_ttu`
 * - `nested_butnot_ttu`
 *
 * Upstream's `ErrorCode: 2000` (a check whose condition
 * parameter the request never supplied) is transcribed as
 * `"refused"`: both engines decline to answer rather than
 * denying.
 *
 * Types and the condition carry a `_b1d` suffix so this
 * fixture cannot collide with another fixture's rows in the
 * shared Postgres and OpenFGA.
 */

const USER = "user_b1d";
const EMPLOYEE = "employee_b1d";
const DU = "directs_user_b1d";
const DE = "directs_employee_b1d";
const UU = "usersets_user_b1d";
const TT = "ttus_b1d";
const XCOND = "xcond_b1d";

/** Upstream's object and subject names, as UUIDs. */
const u = ids(
  [
    "direct_pa_direct_ch/ttu_1",
    "direct_pa_direct_ch/valid",
    "direct_pa_direct_ch/1",
    "direct_pa_direct_ch/ttu_1_invalid",
    "direct_pa_direct_ch/ttu_invalid_group",
    "direct_pa_direct_ch/invalid",
    "or_comp_from_direct_parent/ttu_2",
    "or_comp_from_direct_parent/valid",
    "or_comp_from_direct_parent/2",
    "or_comp_from_direct_parent/ttu_2_invalid",
    "or_comp_from_direct_parent/ttu_invalid_group",
    "or_comp_from_direct_parent/ttu_2_all",
    "or_comp_from_direct_parent/2_all",
    "or_comp_from_direct_parent/invalid",
    "and_comp_from_direct_parent/ttu_3_all",
    "and_comp_from_direct_parent/valid",
    "and_comp_from_direct_parent/ttu_3_partial",
    "and_comp_from_direct_parent/partial",
    "and_comp_from_direct_parent/3",
    "and_comp_from_direct_parent/ttu_invalid_group",
    "and_comp_from_direct_parent/invalid",
    "butnot_comp_from_direct_parent/ttu_4_only_wild",
    "butnot_comp_from_direct_parent/both_wild_computed",
    "butnot_comp_from_direct_parent/ttu_4_only_computed",
    "butnot_comp_from_direct_parent/only_computed",
    "butnot_comp_from_direct_parent/4_only_wild",
    "butnot_comp_from_direct_parent/4_both_wild_computed",
    "butnot_comp_from_direct_parent/4_only_computed",
    "butnot_comp_from_direct_parent/valid",
    "butnot_comp_from_direct_parent/invalid",
    "userset_pa_userset_ch/5",
    "userset_pa_userset_ch/ttu_5",
    "userset_pa_userset_ch/valid",
    "userset_pa_userset_ch/ttu_5_unconnected",
    "userset_pa_userset_ch/ttu_5_unconnected_directuser",
    "userset_pa_userset_ch/ttu_5_unconnected_userset",
    "userset_pa_userset_ch/5_empty_userset",
    "userset_pa_userset_ch/ttu_5_empty_userset",
    "userset_pa_userset_ch/5_empty_direct",
    "userset_pa_userset_ch/ttu_5_empty_direct",
    "userset_pa_userset_ch/unconnected_user_directuser",
    "userset_pa_userset_comp_ch/6",
    "userset_pa_userset_comp_ch/ttu_6",
    "userset_pa_userset_comp_ch/valid",
    "userset_pa_userset_comp_ch/6_disconnected_1",
    "userset_pa_userset_comp_ch/ttu_6_unconnected",
    "userset_pa_userset_comp_ch/6_disconnected_2",
    "userset_pa_userset_comp_ch/ttu_6_disconnected_2",
    "userset_pa_userset_comp_ch/invalid",
    "userset_pa_userset_comp_cond_ch/7",
    "userset_pa_userset_comp_cond_ch/ttu_7",
    "userset_pa_userset_comp_cond_ch/valid",
    "userset_pa_userset_comp_cond_ch/ttu_7_unconnected",
    "userset_pa_userset_comp_cond_ch/7unconnected_from_parent",
    "userset_pa_userset_comp_wild_ch/8",
    "userset_pa_userset_comp_wild_ch/ttu_8",
    "userset_pa_userset_comp_wild_ch/8_unconnected_1",
    "userset_pa_userset_comp_wild_ch/ttu_8_unconnected_1",
    "userset_pa_userset_comp_wild_ch/8_unconnected_2",
    "userset_pa_userset_comp_wild_ch/ttu_8_unconnected_2",
    "userset_pa_userset_comp_wild_ch/user1",
    "userset_pa_userset_comp_wild_ch/user2",
    "userset_pa_userset_comp_wild_cond_ch/9",
    "userset_pa_userset_comp_wild_cond_ch/ttu_9",
    "userset_pa_userset_comp_wild_cond_ch/9_unconnected_1",
    "userset_pa_userset_comp_wild_cond_ch/9_unconnected_2",
    "userset_pa_userset_comp_wild_cond_ch/user1",
    "userset_pa_userset_comp_wild_cond_ch/user2",
    "userset_cond_userset_ch/10",
    "userset_cond_userset_ch/ttu_10",
    "userset_cond_userset_ch/valid",
    "userset_cond_userset_ch/10_disconnected_1",
    "userset_cond_userset_ch/10_disconnected",
    "userset_cond_userset_ch/10_disconnected_2",
    "userset_cond_userset_comp_ch/11",
    "userset_cond_userset_comp_ch/ttu_11",
    "userset_cond_userset_comp_ch/valid",
    "userset_cond_userset_comp_ch/11_disconnected_1",
    "userset_cond_userset_comp_ch/ttu_11_disconnected_1",
    "userset_cond_userset_comp_ch/11_disconnected",
    "userset_cond_userset_comp_ch/11_disconnected_2",
    "userset_cond_userset_comp_ch/ttu_11_disconnected_2",
    "userset_cond_userset_comp_cond_ch/12",
    "userset_cond_userset_comp_cond_ch/ttu_12",
    "userset_cond_userset_comp_cond_ch/valid",
    "userset_cond_userset_comp_cond_ch/12_disconnected",
    "userset_cond_userset_comp_cond_ch/ttu_12_disconnected",
    "userset_cond_userset_comp_cond_ch/ttu_12_udisconnected",
    "userset_cond_userset_comp_wild_ch/13",
    "userset_cond_userset_comp_wild_ch/ttu_13",
    "userset_cond_userset_comp_wild_ch/13_unconnected",
    "userset_cond_userset_comp_wild_ch/ttu_13_unconnected",
    "userset_cond_userset_comp_wild_ch/1",
    "userset_cond_userset_comp_wild_ch/2",
    "userset_cond_userset_comp_wild_cond_ch/14",
    "userset_cond_userset_comp_wild_cond_ch/ttu_14",
    "userset_cond_userset_comp_wild_cond_ch/14_unconnected",
    "userset_cond_userset_comp_wild_cond_ch/ttu_14_unconnected",
    "userset_cond_userset_comp_wild_cond_ch/1",
    "userset_cond_userset_comp_wild_cond_ch/2",
    "or_ttu/15_path_1",
    "or_ttu/ttu_15_path_1",
    "or_ttu/valid_path_1",
    "or_ttu/15_path_2",
    "or_ttu/ttu_15_path_2",
    "or_ttu/valid_path_2",
    "or_ttu/15_path_both",
    "or_ttu/ttu_15_path_both_1",
    "or_ttu/15_path_both_1",
    "or_ttu/valid_both",
    "and_ttu/16_path_1",
    "and_ttu/ttu_16_parent_path_1",
    "and_ttu/ttu_16_parent_path_12",
    "and_ttu/valid1",
    "and_ttu/16_path_2",
    "and_ttu/ttu_16_parent_path_2",
    "and_ttu/valid2",
    "and_ttu/ttu_16_parent_path_22",
    "and_ttu/16_path_3",
    "and_ttu/ttu_16_parent_path_3",
    "and_ttu/valid3",
    "and_ttu/ttu_16_parent_path_32",
    "nested_butnot_ttu/17",
    "nested_butnot_ttu/ttu_17",
    "nested_butnot_ttu/1",
    "nested_butnot_ttu/17_1",
    "nested_butnot_ttu/ttu_17_1",
    "nested_butnot_ttu/2",
  ],
  "d480",
);

// Written in dependency order: a tupleset relation's config
// exists before the tuple-to-userset that names it, so
// `writeRelationConfig`'s tupleset gates can see it.
const CONFIGS: RelationConfig[] = [
  cfg(DE, "direct", { directlyAssignable: [{ type: EMPLOYEE }] }),
  cfg(DE, "computed", { computedUserset: "direct" }),
  cfg(DE, "direct_cond", {
    directlyAssignable: [{ type: EMPLOYEE, condition: XCOND }],
  }),
  cfg(DE, "direct_wild", {
    directlyAssignable: [{ type: EMPLOYEE, wildcard: true }],
  }),
  cfg(DE, "direct_wild_cond", {
    directlyAssignable: [{ type: EMPLOYEE, wildcard: true, condition: XCOND }],
  }),
  cfg(DU, "direct_cond", {
    directlyAssignable: [{ type: USER, condition: XCOND }],
  }),
  cfg(DU, "computed_cond", { computedUserset: "direct_cond" }),
  cfg(DU, "direct_wild", {
    directlyAssignable: [{ type: USER, wildcard: true }],
  }),
  cfg(DU, "computed_wild", { computedUserset: "direct_wild" }),
  cfg(DU, "and_computed", {
    intersection: [
      { type: "computedUserset", relation: "computed_cond" },
      { type: "computedUserset", relation: "computed_wild" },
    ],
  }),
  cfg(DU, "direct_wild_cond", {
    directlyAssignable: [{ type: USER, wildcard: true, condition: XCOND }],
  }),
  cfg(DU, "computed_wild_cond", { computedUserset: "direct_wild_cond" }),
  cfg(DU, "direct", { directlyAssignable: [{ type: USER }] }),
  cfg(DU, "computed", { computedUserset: "direct" }),
  cfg(DU, "computed_computed", { computedUserset: "computed" }),
  cfg(DU, "butnot_computed", {
    computedUserset: "computed_wild_cond",
    excludedBy: "computed_computed",
  }),
  cfg(DU, "or_computed", {
    impliedBy: ["computed", "computed_cond", "direct_wild"],
  }),
  cfg(TT, "direct_cond_parent", {
    directlyAssignable: [{ type: DU, condition: XCOND }],
  }),
  cfg(TT, "and_comp_from_direct_parent", {
    tupleToUserset: [
      { tupleset: "direct_cond_parent", computedUserset: "and_computed" },
    ],
  }),
  cfg(TT, "direct_parent", { directlyAssignable: [{ type: DU }] }),
  cfg(TT, "or_comp_from_direct_parent", {
    tupleToUserset: [
      { tupleset: "direct_parent", computedUserset: "or_computed" },
    ],
  }),
  cfg(TT, "mult_parent_types", {
    directlyAssignable: [{ type: DU }, { type: DE }],
  }),
  cfg(TT, "direct_pa_direct_ch", {
    tupleToUserset: [
      { tupleset: "mult_parent_types", computedUserset: "direct" },
    ],
  }),
  cfg(TT, "and_ttu", {
    intersection: [
      { type: "computedUserset", relation: "or_comp_from_direct_parent" },
      { type: "computedUserset", relation: "direct_pa_direct_ch" },
    ],
  }),
  cfg(TT, "butnot_comp_from_direct_parent", {
    tupleToUserset: [
      { tupleset: "direct_cond_parent", computedUserset: "butnot_computed" },
    ],
  }),
  cfg(TT, "mult_parent_types_cond", {
    directlyAssignable: [
      { type: DU, condition: XCOND },
      { type: DE, condition: XCOND },
    ],
  }),
  cfg(TT, "direct_cond_pa_direct_ch", {
    tupleToUserset: [
      { tupleset: "mult_parent_types_cond", computedUserset: "direct" },
    ],
  }),
  cfg(TT, "userset_parent", { directlyAssignable: [{ type: UU }] }),
  cfg(UU, "userset_to_computed_wild", {
    directlyAssignable: [
      { type: DU, relation: "computed_wild" },
      { type: DE, relation: "direct_wild" },
    ],
  }),
  cfg(TT, "userset_pa_userset_comp_wild_ch", {
    tupleToUserset: [
      {
        tupleset: "userset_parent",
        computedUserset: "userset_to_computed_wild",
      },
    ],
  }),
  cfg(TT, "nested_butnot_ttu", {
    computedUserset: "or_comp_from_direct_parent",
    excludedBy: "userset_pa_userset_comp_wild_ch",
  }),
  cfg(TT, "or_ttu", {
    impliedBy: ["direct_pa_direct_ch", "direct_cond_pa_direct_ch"],
  }),
  cfg(TT, "userset_cond_parent", {
    directlyAssignable: [{ type: UU, condition: XCOND }],
  }),
  cfg(UU, "userset", {
    directlyAssignable: [
      { type: DU, relation: "direct" },
      { type: DE, relation: "direct" },
    ],
  }),
  cfg(TT, "userset_cond_userset_ch", {
    tupleToUserset: [
      { tupleset: "userset_cond_parent", computedUserset: "userset" },
    ],
  }),
  cfg(UU, "userset_to_computed", {
    directlyAssignable: [
      { type: DU, relation: "computed" },
      { type: DE, relation: "computed" },
    ],
  }),
  cfg(TT, "userset_cond_userset_comp_ch", {
    tupleToUserset: [
      {
        tupleset: "userset_cond_parent",
        computedUserset: "userset_to_computed",
      },
    ],
  }),
  cfg(UU, "userset_to_computed_cond", {
    directlyAssignable: [
      { type: DU, relation: "computed_cond" },
      { type: DE, relation: "direct_cond" },
    ],
  }),
  cfg(TT, "userset_cond_userset_comp_cond_ch", {
    tupleToUserset: [
      {
        tupleset: "userset_cond_parent",
        computedUserset: "userset_to_computed_cond",
      },
    ],
  }),
  cfg(TT, "userset_cond_userset_comp_wild_ch", {
    tupleToUserset: [
      {
        tupleset: "userset_cond_parent",
        computedUserset: "userset_to_computed_wild",
      },
    ],
  }),
  cfg(UU, "userset_to_computed_wild_cond", {
    directlyAssignable: [
      { type: DU, relation: "direct_wild_cond" },
      { type: DE, relation: "direct_wild_cond" },
    ],
  }),
  cfg(TT, "userset_cond_userset_comp_wild_cond_ch", {
    tupleToUserset: [
      {
        tupleset: "userset_cond_parent",
        computedUserset: "userset_to_computed_wild_cond",
      },
    ],
  }),
  cfg(TT, "userset_pa_userset_ch", {
    tupleToUserset: [
      { tupleset: "userset_parent", computedUserset: "userset" },
    ],
  }),
  cfg(TT, "userset_pa_userset_comp_ch", {
    tupleToUserset: [
      { tupleset: "userset_parent", computedUserset: "userset_to_computed" },
    ],
  }),
  cfg(TT, "userset_pa_userset_comp_cond_ch", {
    tupleToUserset: [
      {
        tupleset: "userset_parent",
        computedUserset: "userset_to_computed_cond",
      },
    ],
  }),
  cfg(TT, "userset_pa_userset_comp_wild_cond_ch", {
    tupleToUserset: [
      {
        tupleset: "userset_parent",
        computedUserset: "userset_to_computed_wild_cond",
      },
    ],
  }),
];

const STAGES: Stage[] = [
  {
    name: "direct_pa_direct_ch",
    tuples: [
      {
        objectType: DU,
        objectId: u("direct_pa_direct_ch/ttu_1"),
        relation: "direct",
        subjectType: USER,
        subjectId: u("direct_pa_direct_ch/valid"),
      },
      {
        objectType: TT,
        objectId: u("direct_pa_direct_ch/1"),
        relation: "mult_parent_types",
        subjectType: DU,
        subjectId: u("direct_pa_direct_ch/ttu_1"),
      },
      {
        objectType: DU,
        objectId: u("direct_pa_direct_ch/ttu_1_invalid"),
        relation: "direct",
        subjectType: USER,
        subjectId: u("direct_pa_direct_ch/ttu_invalid_group"),
      },
    ],
    cases: [
      {
        name: "direct_pa_direct_ch/valid_user",
        objectType: TT,
        objectId: u("direct_pa_direct_ch/1"),
        relation: "direct_pa_direct_ch",
        subjectType: USER,
        subjectId: u("direct_pa_direct_ch/valid"),
        expected: true,
      },
      {
        name: "direct_pa_direct_ch/invalid_user",
        objectType: TT,
        objectId: u("direct_pa_direct_ch/1"),
        relation: "direct_pa_direct_ch",
        subjectType: USER,
        subjectId: u("direct_pa_direct_ch/invalid"),
        expected: false,
      },
      {
        name: "direct_pa_direct_ch/invalid_group",
        objectType: TT,
        objectId: u("direct_pa_direct_ch/1"),
        relation: "direct_pa_direct_ch",
        subjectType: USER,
        subjectId: u("direct_pa_direct_ch/ttu_invalid_group"),
        expected: false,
      },
      {
        name: "direct_pa_direct_ch/invalid_object",
        objectType: TT,
        objectId: u("direct_pa_direct_ch/invalid"),
        relation: "direct_pa_direct_ch",
        subjectType: USER,
        subjectId: u("direct_pa_direct_ch/valid"),
        expected: false,
      },
    ],
  },
  {
    name: "or_comp_from_direct_parent",
    tuples: [
      {
        objectType: DU,
        objectId: u("or_comp_from_direct_parent/ttu_2"),
        relation: "direct",
        subjectType: USER,
        subjectId: u("or_comp_from_direct_parent/valid"),
      },
      {
        objectType: TT,
        objectId: u("or_comp_from_direct_parent/2"),
        relation: "direct_parent",
        subjectType: DU,
        subjectId: u("or_comp_from_direct_parent/ttu_2"),
      },
      {
        objectType: DU,
        objectId: u("or_comp_from_direct_parent/ttu_2_invalid"),
        relation: "direct",
        subjectType: USER,
        subjectId: u("or_comp_from_direct_parent/ttu_invalid_group"),
      },
      {
        objectType: DU,
        objectId: u("or_comp_from_direct_parent/ttu_2_all"),
        relation: "direct_wild",
        subjectType: USER,
        subjectId: "*",
      },
      {
        objectType: TT,
        objectId: u("or_comp_from_direct_parent/2_all"),
        relation: "direct_parent",
        subjectType: DU,
        subjectId: u("or_comp_from_direct_parent/ttu_2_all"),
      },
    ],
    cases: [
      {
        name: "or_comp_from_direct_parent/or_computed_valid",
        objectType: TT,
        objectId: u("or_comp_from_direct_parent/2"),
        relation: "or_comp_from_direct_parent",
        subjectType: USER,
        subjectId: u("or_comp_from_direct_parent/valid"),
        expected: true,
      },
      {
        name: "or_comp_from_direct_parent/or_computed_valid_second_child_match",
        objectType: TT,
        objectId: u("or_comp_from_direct_parent/2_all"),
        relation: "or_comp_from_direct_parent",
        subjectType: USER,
        subjectId: u("or_comp_from_direct_parent/valid"),
        expected: true,
      },
      {
        name: "or_comp_from_direct_parent/invalid_user",
        objectType: TT,
        objectId: u("or_comp_from_direct_parent/2"),
        relation: "or_comp_from_direct_parent",
        subjectType: USER,
        subjectId: u("or_comp_from_direct_parent/ttu_invalid_group"),
        expected: false,
      },
      {
        name: "or_comp_from_direct_parent/invalid_object",
        objectType: TT,
        objectId: u("or_comp_from_direct_parent/invalid"),
        relation: "or_comp_from_direct_parent",
        subjectType: USER,
        subjectId: u("or_comp_from_direct_parent/valid"),
        expected: false,
      },
    ],
  },
  {
    name: "and_comp_from_direct_parent",
    tuples: [
      {
        objectType: DU,
        objectId: u("and_comp_from_direct_parent/ttu_3_all"),
        relation: "direct_cond",
        subjectType: USER,
        subjectId: u("and_comp_from_direct_parent/valid"),
        conditionName: XCOND,
      },
      {
        objectType: DU,
        objectId: u("and_comp_from_direct_parent/ttu_3_all"),
        relation: "direct_wild",
        subjectType: USER,
        subjectId: "*",
      },
      {
        objectType: DU,
        objectId: u("and_comp_from_direct_parent/ttu_3_partial"),
        relation: "direct_cond",
        subjectType: USER,
        subjectId: u("and_comp_from_direct_parent/partial"),
        conditionName: XCOND,
      },
      {
        objectType: TT,
        objectId: u("and_comp_from_direct_parent/3"),
        relation: "direct_cond_parent",
        subjectType: DU,
        subjectId: u("and_comp_from_direct_parent/ttu_3_all"),
        conditionName: XCOND,
      },
      {
        objectType: TT,
        objectId: u("and_comp_from_direct_parent/3"),
        relation: "direct_cond_parent",
        subjectType: DU,
        subjectId: u("and_comp_from_direct_parent/ttu_3_partial"),
        conditionName: XCOND,
      },
    ],
    cases: [
      {
        name: "and_comp_from_direct_parent/and_computed_valid",
        objectType: TT,
        objectId: u("and_comp_from_direct_parent/3"),
        relation: "and_comp_from_direct_parent",
        subjectType: USER,
        subjectId: u("and_comp_from_direct_parent/valid"),
        context: { x: "1" },
        expected: true,
      },
      {
        name: "and_comp_from_direct_parent/invalid_user",
        objectType: TT,
        objectId: u("and_comp_from_direct_parent/3"),
        relation: "and_comp_from_direct_parent",
        subjectType: USER,
        subjectId: u("and_comp_from_direct_parent/ttu_invalid_group"),
        context: { x: "1" },
        expected: false,
      },
      {
        name: "and_comp_from_direct_parent/invalid_user_partial",
        objectType: TT,
        objectId: u("and_comp_from_direct_parent/3"),
        relation: "and_comp_from_direct_parent",
        subjectType: USER,
        subjectId: u("and_comp_from_direct_parent/partial"),
        context: { x: "1" },
        expected: false,
      },
      {
        name: "and_comp_from_direct_parent/invalid_object",
        objectType: TT,
        objectId: u("and_comp_from_direct_parent/invalid"),
        relation: "and_comp_from_direct_parent",
        subjectType: USER,
        subjectId: u("and_comp_from_direct_parent/valid"),
        context: { x: "1" },
        expected: false,
      },
    ],
  },
  {
    name: "butnot_comp_from_direct_parent",
    tuples: [
      {
        objectType: DU,
        objectId: u("butnot_comp_from_direct_parent/ttu_4_only_wild"),
        relation: "direct_wild_cond",
        subjectType: USER,
        subjectId: "*",
        conditionName: XCOND,
      },
      {
        objectType: DU,
        objectId: u("butnot_comp_from_direct_parent/both_wild_computed"),
        relation: "direct",
        subjectType: USER,
        subjectId: u("butnot_comp_from_direct_parent/both_wild_computed"),
      },
      {
        objectType: DU,
        objectId: u("butnot_comp_from_direct_parent/both_wild_computed"),
        relation: "direct_wild_cond",
        subjectType: USER,
        subjectId: "*",
        conditionName: XCOND,
      },
      {
        objectType: DU,
        objectId: u("butnot_comp_from_direct_parent/ttu_4_only_computed"),
        relation: "direct",
        subjectType: USER,
        subjectId: u("butnot_comp_from_direct_parent/only_computed"),
      },
      {
        objectType: TT,
        objectId: u("butnot_comp_from_direct_parent/4_only_wild"),
        relation: "direct_cond_parent",
        subjectType: DU,
        subjectId: u("butnot_comp_from_direct_parent/ttu_4_only_wild"),
        conditionName: XCOND,
      },
      {
        objectType: TT,
        objectId: u("butnot_comp_from_direct_parent/4_both_wild_computed"),
        relation: "direct_cond_parent",
        subjectType: DU,
        subjectId: u("butnot_comp_from_direct_parent/both_wild_computed"),
        conditionName: XCOND,
      },
      {
        objectType: TT,
        objectId: u("butnot_comp_from_direct_parent/4_only_computed"),
        relation: "direct_cond_parent",
        subjectType: DU,
        subjectId: u("butnot_comp_from_direct_parent/ttu_4_only_computed"),
        conditionName: XCOND,
      },
    ],
    cases: [
      {
        name: "butnot_comp_from_direct_parent/butnot_ok",
        objectType: TT,
        objectId: u("butnot_comp_from_direct_parent/4_only_wild"),
        relation: "butnot_comp_from_direct_parent",
        subjectType: USER,
        subjectId: u("butnot_comp_from_direct_parent/valid"),
        context: { x: "1" },
        expected: true,
      },
      {
        name: "butnot_comp_from_direct_parent/butnot_both_match",
        objectType: TT,
        objectId: u("butnot_comp_from_direct_parent/4_both_wild_computed"),
        relation: "butnot_comp_from_direct_parent",
        subjectType: USER,
        subjectId: u("butnot_comp_from_direct_parent/both_wild_computed"),
        context: { x: "1" },
        expected: false,
      },
      {
        name: "butnot_comp_from_direct_parent/butnot_only_computed",
        objectType: TT,
        objectId: u("butnot_comp_from_direct_parent/4_only_computed"),
        relation: "butnot_comp_from_direct_parent",
        subjectType: USER,
        subjectId: u("butnot_comp_from_direct_parent/only_computed"),
        context: { x: "1" },
        expected: false,
      },
      {
        name: "butnot_comp_from_direct_parent/invalid_object",
        objectType: TT,
        objectId: u("butnot_comp_from_direct_parent/invalid"),
        relation: "butnot_comp_from_direct_parent",
        subjectType: USER,
        subjectId: u("butnot_comp_from_direct_parent/valid"),
        context: { x: "1" },
        expected: false,
      },
    ],
  },
  {
    name: "userset_pa_userset_ch",
    tuples: [
      {
        objectType: TT,
        objectId: u("userset_pa_userset_ch/5"),
        relation: "userset_parent",
        subjectType: UU,
        subjectId: u("userset_pa_userset_ch/ttu_5"),
      },
      {
        objectType: UU,
        objectId: u("userset_pa_userset_ch/ttu_5"),
        relation: "userset",
        subjectType: DU,
        subjectId: u("userset_pa_userset_ch/ttu_5"),
        subjectRelation: "direct",
      },
      {
        objectType: DU,
        objectId: u("userset_pa_userset_ch/ttu_5"),
        relation: "direct",
        subjectType: USER,
        subjectId: u("userset_pa_userset_ch/valid"),
      },
      {
        objectType: DU,
        objectId: u("userset_pa_userset_ch/ttu_5_unconnected"),
        relation: "direct",
        subjectType: USER,
        subjectId: u("userset_pa_userset_ch/ttu_5_unconnected_directuser"),
      },
      {
        objectType: DU,
        objectId: u("userset_pa_userset_ch/ttu_5_unconnected_userset"),
        relation: "direct",
        subjectType: USER,
        subjectId: u("userset_pa_userset_ch/ttu_5_unconnected_userset"),
      },
      {
        objectType: UU,
        objectId: u("userset_pa_userset_ch/ttu_5_unconnected_userset"),
        relation: "userset",
        subjectType: DU,
        subjectId: u("userset_pa_userset_ch/ttu_5_unconnected_userset"),
        subjectRelation: "direct",
      },
      {
        objectType: TT,
        objectId: u("userset_pa_userset_ch/5_empty_userset"),
        relation: "userset_parent",
        subjectType: UU,
        subjectId: u("userset_pa_userset_ch/ttu_5_empty_userset"),
      },
      {
        objectType: TT,
        objectId: u("userset_pa_userset_ch/5_empty_direct"),
        relation: "userset_parent",
        subjectType: UU,
        subjectId: u("userset_pa_userset_ch/ttu_5_empty_direct"),
      },
      {
        objectType: UU,
        objectId: u("userset_pa_userset_ch/ttu_5_empty_direct"),
        relation: "userset",
        subjectType: DU,
        subjectId: u("userset_pa_userset_ch/ttu_5_empty_direct"),
        subjectRelation: "direct",
      },
    ],
    cases: [
      {
        name: "userset_pa_userset_ch/userset_parent_userset_ch",
        objectType: TT,
        objectId: u("userset_pa_userset_ch/5"),
        relation: "userset_pa_userset_ch",
        subjectType: USER,
        subjectId: u("userset_pa_userset_ch/valid"),
        expected: true,
      },
      {
        name: "userset_pa_userset_ch/user_directuser_not_connected",
        objectType: TT,
        objectId: u("userset_pa_userset_ch/5"),
        relation: "userset_pa_userset_ch",
        subjectType: USER,
        subjectId: u("userset_pa_userset_ch/unconnected_user_directuser"),
        expected: false,
      },
      {
        name: "userset_pa_userset_ch/directuser_userset_not_connected",
        objectType: TT,
        objectId: u("userset_pa_userset_ch/5"),
        relation: "userset_pa_userset_ch",
        subjectType: USER,
        subjectId: u("userset_pa_userset_ch/ttu_5_unconnected_directuser"),
        expected: false,
      },
      {
        name: "userset_pa_userset_ch/userset_ttu_not_connected",
        objectType: TT,
        objectId: u("userset_pa_userset_ch/5"),
        relation: "userset_pa_userset_ch",
        subjectType: USER,
        subjectId: u("userset_pa_userset_ch/ttu_5_unconnected_userset"),
        expected: false,
      },
      {
        name: "userset_pa_userset_ch/empty_userset",
        objectType: TT,
        objectId: u("userset_pa_userset_ch/5_empty_userset"),
        relation: "userset_pa_userset_ch",
        subjectType: USER,
        subjectId: u("userset_pa_userset_ch/valid"),
        expected: false,
      },
      {
        name: "userset_pa_userset_ch/empty_direct",
        objectType: TT,
        objectId: u("userset_pa_userset_ch/5_empty_direct"),
        relation: "userset_pa_userset_ch",
        subjectType: USER,
        subjectId: u("userset_pa_userset_ch/valid"),
        expected: false,
      },
    ],
  },
  {
    name: "userset_pa_userset_comp_ch",
    tuples: [
      {
        objectType: TT,
        objectId: u("userset_pa_userset_comp_ch/6"),
        relation: "userset_parent",
        subjectType: UU,
        subjectId: u("userset_pa_userset_comp_ch/ttu_6"),
      },
      {
        objectType: UU,
        objectId: u("userset_pa_userset_comp_ch/ttu_6"),
        relation: "userset_to_computed",
        subjectType: DU,
        subjectId: u("userset_pa_userset_comp_ch/ttu_6"),
        subjectRelation: "computed",
      },
      {
        objectType: DU,
        objectId: u("userset_pa_userset_comp_ch/ttu_6"),
        relation: "direct",
        subjectType: USER,
        subjectId: u("userset_pa_userset_comp_ch/valid"),
      },
      {
        objectType: TT,
        objectId: u("userset_pa_userset_comp_ch/6_disconnected_1"),
        relation: "userset_parent",
        subjectType: UU,
        subjectId: u("userset_pa_userset_comp_ch/ttu_6_unconnected"),
      },
      {
        objectType: UU,
        objectId: u("userset_pa_userset_comp_ch/ttu_6_unconnected"),
        relation: "userset_to_computed",
        subjectType: DU,
        subjectId: u("userset_pa_userset_comp_ch/ttu_6_unconnected"),
        subjectRelation: "computed",
      },
      {
        objectType: TT,
        objectId: u("userset_pa_userset_comp_ch/6_disconnected_2"),
        relation: "userset_parent",
        subjectType: UU,
        subjectId: u("userset_pa_userset_comp_ch/ttu_6_disconnected_2"),
      },
    ],
    cases: [
      {
        name: "userset_pa_userset_comp_ch/path_to_user",
        objectType: TT,
        objectId: u("userset_pa_userset_comp_ch/6"),
        relation: "userset_pa_userset_comp_ch",
        subjectType: USER,
        subjectId: u("userset_pa_userset_comp_ch/valid"),
        expected: true,
      },
      {
        name: "userset_pa_userset_comp_ch/no_path_to_user",
        objectType: TT,
        objectId: u("userset_pa_userset_comp_ch/6"),
        relation: "userset_pa_userset_comp_ch",
        subjectType: USER,
        subjectId: u("userset_pa_userset_comp_ch/invalid"),
        expected: false,
      },
      {
        name: "userset_pa_userset_comp_ch/no_path_to_user_because_not_part_of_userset",
        objectType: TT,
        objectId: u("userset_pa_userset_comp_ch/6_disconnected_1"),
        relation: "userset_pa_userset_comp_ch",
        subjectType: USER,
        subjectId: u("userset_pa_userset_comp_ch/valid"),
        expected: false,
      },
      {
        name: "userset_pa_userset_comp_ch/no_path_to_user_because_parent_not_linked_to_anything",
        objectType: TT,
        objectId: u("userset_pa_userset_comp_ch/6_disconnected_2"),
        relation: "userset_pa_userset_comp_ch",
        subjectType: USER,
        subjectId: u("userset_pa_userset_comp_ch/valid"),
        expected: false,
      },
    ],
  },
  {
    name: "userset_pa_userset_comp_cond_ch",
    tuples: [
      {
        objectType: TT,
        objectId: u("userset_pa_userset_comp_cond_ch/7"),
        relation: "userset_parent",
        subjectType: UU,
        subjectId: u("userset_pa_userset_comp_cond_ch/ttu_7"),
      },
      {
        objectType: UU,
        objectId: u("userset_pa_userset_comp_cond_ch/ttu_7"),
        relation: "userset_to_computed_cond",
        subjectType: DU,
        subjectId: u("userset_pa_userset_comp_cond_ch/ttu_7"),
        subjectRelation: "computed_cond",
      },
      {
        objectType: DU,
        objectId: u("userset_pa_userset_comp_cond_ch/ttu_7"),
        relation: "direct_cond",
        subjectType: USER,
        subjectId: u("userset_pa_userset_comp_cond_ch/valid"),
        conditionName: XCOND,
      },
      {
        objectType: DU,
        objectId: u("userset_pa_userset_comp_cond_ch/ttu_7_unconnected"),
        relation: "direct_cond",
        subjectType: USER,
        subjectId: u(
          "userset_pa_userset_comp_cond_ch/7unconnected_from_parent",
        ),
        conditionName: XCOND,
      },
    ],
    cases: [
      {
        name: "userset_pa_userset_comp_cond_ch/path_to_user_and_condition_evaluates_true",
        objectType: TT,
        objectId: u("userset_pa_userset_comp_cond_ch/7"),
        relation: "userset_pa_userset_comp_cond_ch",
        subjectType: USER,
        subjectId: u("userset_pa_userset_comp_cond_ch/valid"),
        context: { x: "1" },
        expected: true,
      },
      {
        name: "userset_pa_userset_comp_cond_ch/no_path_to_user_and_condition_evaluates_false",
        objectType: TT,
        objectId: u("userset_pa_userset_comp_cond_ch/7"),
        relation: "userset_pa_userset_comp_cond_ch",
        subjectType: USER,
        subjectId: u("userset_pa_userset_comp_cond_ch/valid"),
        context: { x: "2" },
        expected: false,
      },
      {
        name: "userset_pa_userset_comp_cond_ch/no_path_to_user_even_if_condition_true",
        objectType: TT,
        objectId: u("userset_pa_userset_comp_cond_ch/7"),
        relation: "userset_pa_userset_comp_cond_ch",
        subjectType: USER,
        subjectId: u(
          "userset_pa_userset_comp_cond_ch/7unconnected_from_parent",
        ),
        context: { x: "1" },
        expected: false,
      },
      {
        name: "userset_pa_userset_comp_cond_ch/no_path_to_user_and_condition_false",
        objectType: TT,
        objectId: u("userset_pa_userset_comp_cond_ch/7"),
        relation: "userset_pa_userset_comp_cond_ch",
        subjectType: USER,
        subjectId: u(
          "userset_pa_userset_comp_cond_ch/7unconnected_from_parent",
        ),
        context: { x: "2" },
        expected: false,
      },
    ],
  },
  {
    name: "userset_pa_userset_comp_wild_ch",
    tuples: [
      {
        objectType: TT,
        objectId: u("userset_pa_userset_comp_wild_ch/8"),
        relation: "userset_parent",
        subjectType: UU,
        subjectId: u("userset_pa_userset_comp_wild_ch/ttu_8"),
      },
      {
        objectType: UU,
        objectId: u("userset_pa_userset_comp_wild_ch/ttu_8"),
        relation: "userset_to_computed_wild",
        subjectType: DU,
        subjectId: u("userset_pa_userset_comp_wild_ch/ttu_8"),
        subjectRelation: "computed_wild",
      },
      {
        objectType: DU,
        objectId: u("userset_pa_userset_comp_wild_ch/ttu_8"),
        relation: "direct_wild",
        subjectType: USER,
        subjectId: "*",
      },
      {
        objectType: TT,
        objectId: u("userset_pa_userset_comp_wild_ch/8_unconnected_1"),
        relation: "userset_parent",
        subjectType: UU,
        subjectId: u("userset_pa_userset_comp_wild_ch/ttu_8_unconnected_1"),
      },
      {
        objectType: TT,
        objectId: u("userset_pa_userset_comp_wild_ch/8_unconnected_2"),
        relation: "userset_parent",
        subjectType: UU,
        subjectId: u("userset_pa_userset_comp_wild_ch/ttu_8_unconnected_2"),
      },
      {
        objectType: UU,
        objectId: u("userset_pa_userset_comp_wild_ch/ttu_8_unconnected_2"),
        relation: "userset_to_computed_wild",
        subjectType: DU,
        subjectId: u("userset_pa_userset_comp_wild_ch/ttu_8_unconnected_2"),
        subjectRelation: "computed_wild",
      },
    ],
    cases: [
      {
        name: "userset_pa_userset_comp_wild_ch/path_to_random_user_and_condition_is_true",
        objectType: TT,
        objectId: u("userset_pa_userset_comp_wild_ch/8"),
        relation: "userset_pa_userset_comp_wild_ch",
        subjectType: USER,
        subjectId: u("userset_pa_userset_comp_wild_ch/user1"),
        context: { x: "1" },
        expected: true,
      },
      {
        name: "userset_pa_userset_comp_wild_ch/path_to_random_user_and_condition_is_false",
        objectType: TT,
        objectId: u("userset_pa_userset_comp_wild_ch/8"),
        relation: "userset_pa_userset_comp_wild_ch",
        subjectType: USER,
        subjectId: u("userset_pa_userset_comp_wild_ch/user1"),
        context: { x: "2" },
        expected: true,
      },
      {
        name: "userset_pa_userset_comp_wild_ch/path_to_another_random_user_and_condition_is_true",
        objectType: TT,
        objectId: u("userset_pa_userset_comp_wild_ch/8"),
        relation: "userset_pa_userset_comp_wild_ch",
        subjectType: USER,
        subjectId: u("userset_pa_userset_comp_wild_ch/user2"),
        context: { x: "1" },
        expected: true,
      },
      {
        name: "userset_pa_userset_comp_wild_ch/no_path_to_user_even_if_condition_true_because_parent_not_linked",
        objectType: TT,
        objectId: u("userset_pa_userset_comp_wild_ch/8_unconnected_1"),
        relation: "userset_pa_userset_comp_wild_ch",
        subjectType: USER,
        subjectId: u("userset_pa_userset_comp_wild_ch/user1"),
        context: { x: "1" },
        expected: false,
      },
      {
        name: "userset_pa_userset_comp_wild_ch/no_path_to_user_even_if_condition_true_because_user_not_part_of_userset",
        objectType: TT,
        objectId: u("userset_pa_userset_comp_wild_ch/8_unconnected_2"),
        relation: "userset_pa_userset_comp_wild_ch",
        subjectType: USER,
        subjectId: u("userset_pa_userset_comp_wild_ch/user1"),
        context: { x: "1" },
        expected: false,
      },
    ],
  },
  {
    name: "userset_pa_userset_comp_wild_cond_ch",
    tuples: [
      {
        objectType: TT,
        objectId: u("userset_pa_userset_comp_wild_cond_ch/9"),
        relation: "userset_parent",
        subjectType: UU,
        subjectId: u("userset_pa_userset_comp_wild_cond_ch/ttu_9"),
      },
      {
        objectType: UU,
        objectId: u("userset_pa_userset_comp_wild_cond_ch/ttu_9"),
        relation: "userset_to_computed_wild_cond",
        subjectType: DU,
        subjectId: u("userset_pa_userset_comp_wild_cond_ch/ttu_9"),
        subjectRelation: "direct_wild_cond",
      },
      {
        objectType: DU,
        objectId: u("userset_pa_userset_comp_wild_cond_ch/ttu_9"),
        relation: "direct_wild_cond",
        subjectType: USER,
        subjectId: "*",
        conditionName: XCOND,
      },
      {
        objectType: TT,
        objectId: u("userset_pa_userset_comp_wild_cond_ch/9_unconnected_1"),
        relation: "userset_parent",
        subjectType: UU,
        subjectId: u("userset_pa_userset_comp_wild_cond_ch/9_unconnected_1"),
      },
      {
        objectType: TT,
        objectId: u("userset_pa_userset_comp_wild_cond_ch/9_unconnected_2"),
        relation: "userset_parent",
        subjectType: UU,
        subjectId: u("userset_pa_userset_comp_wild_cond_ch/9_unconnected_2"),
      },
      {
        objectType: UU,
        objectId: u("userset_pa_userset_comp_wild_cond_ch/9_unconnected_2"),
        relation: "userset_to_computed_wild_cond",
        subjectType: DU,
        subjectId: u("userset_pa_userset_comp_wild_cond_ch/9_unconnected_2"),
        subjectRelation: "direct_wild_cond",
      },
    ],
    cases: [
      {
        name: "userset_pa_userset_comp_wild_cond_ch/path_to_random_user_and_condition_is_true",
        objectType: TT,
        objectId: u("userset_pa_userset_comp_wild_cond_ch/9"),
        relation: "userset_pa_userset_comp_wild_cond_ch",
        subjectType: USER,
        subjectId: u("userset_pa_userset_comp_wild_cond_ch/user1"),
        context: { x: "1" },
        expected: true,
      },
      {
        name: "userset_pa_userset_comp_wild_cond_ch/path_to_another_random_user_and_condition_is_true",
        objectType: TT,
        objectId: u("userset_pa_userset_comp_wild_cond_ch/9"),
        relation: "userset_pa_userset_comp_wild_cond_ch",
        subjectType: USER,
        subjectId: u("userset_pa_userset_comp_wild_cond_ch/user2"),
        context: { x: "1" },
        expected: true,
      },
      {
        name: "userset_pa_userset_comp_wild_cond_ch/no_path_to_random_user_because_condition_evaluates_false",
        objectType: TT,
        objectId: u("userset_pa_userset_comp_wild_cond_ch/9"),
        relation: "userset_pa_userset_comp_wild_cond_ch",
        subjectType: USER,
        subjectId: u("userset_pa_userset_comp_wild_cond_ch/user1"),
        context: { x: "2" },
        expected: false,
      },
      {
        name: "userset_pa_userset_comp_wild_cond_ch/no_path_to_another_random_user_because_condition_evaluates_false",
        objectType: TT,
        objectId: u("userset_pa_userset_comp_wild_cond_ch/9"),
        relation: "userset_pa_userset_comp_wild_cond_ch",
        subjectType: USER,
        subjectId: u("userset_pa_userset_comp_wild_cond_ch/user2"),
        context: { x: "2" },
        expected: false,
      },
      {
        name: "userset_pa_userset_comp_wild_cond_ch/no_path_to_user_even_if_condition_true_because_parent_not_linked",
        objectType: TT,
        objectId: u("userset_pa_userset_comp_wild_cond_ch/9_unconnected_1"),
        relation: "userset_pa_userset_comp_wild_cond_ch",
        subjectType: USER,
        subjectId: u("userset_pa_userset_comp_wild_cond_ch/user1"),
        context: { x: "1" },
        expected: false,
      },
      {
        name: "userset_pa_userset_comp_wild_cond_ch/no_path_to_user_even_if_condition_true_because_user_not_part_of_userset",
        objectType: TT,
        objectId: u("userset_pa_userset_comp_wild_cond_ch/9_unconnected_2"),
        relation: "userset_pa_userset_comp_wild_cond_ch",
        subjectType: USER,
        subjectId: u("userset_pa_userset_comp_wild_cond_ch/user1"),
        context: { x: "1" },
        expected: false,
      },
    ],
  },
  {
    name: "userset_cond_userset_ch",
    tuples: [
      {
        objectType: TT,
        objectId: u("userset_cond_userset_ch/10"),
        relation: "userset_cond_parent",
        subjectType: UU,
        subjectId: u("userset_cond_userset_ch/ttu_10"),
        conditionName: XCOND,
      },
      {
        objectType: UU,
        objectId: u("userset_cond_userset_ch/ttu_10"),
        relation: "userset",
        subjectType: DU,
        subjectId: u("userset_cond_userset_ch/ttu_10"),
        subjectRelation: "direct",
      },
      {
        objectType: DU,
        objectId: u("userset_cond_userset_ch/ttu_10"),
        relation: "direct",
        subjectType: USER,
        subjectId: u("userset_cond_userset_ch/valid"),
      },
      {
        objectType: UU,
        objectId: u("userset_cond_userset_ch/ttu_10"),
        relation: "userset",
        subjectType: DE,
        subjectId: u("userset_cond_userset_ch/ttu_10"),
        subjectRelation: "direct",
      },
      {
        objectType: DE,
        objectId: u("userset_cond_userset_ch/ttu_10"),
        relation: "direct",
        subjectType: EMPLOYEE,
        subjectId: u("userset_cond_userset_ch/valid"),
      },
      {
        objectType: TT,
        objectId: u("userset_cond_userset_ch/10_disconnected_1"),
        relation: "userset_cond_parent",
        subjectType: UU,
        subjectId: u("userset_cond_userset_ch/10_disconnected_1"),
        conditionName: XCOND,
      },
      {
        objectType: UU,
        objectId: u("userset_cond_userset_ch/10_disconnected_1"),
        relation: "userset",
        subjectType: DU,
        subjectId: u("userset_cond_userset_ch/10_disconnected"),
        subjectRelation: "direct",
      },
      {
        objectType: TT,
        objectId: u("userset_cond_userset_ch/10_disconnected_2"),
        relation: "userset_cond_parent",
        subjectType: UU,
        subjectId: u("userset_cond_userset_ch/10_disconnected_2"),
        conditionName: XCOND,
      },
    ],
    cases: [
      {
        name: "userset_cond_userset_ch/path_to_user_and_cond_is_true",
        objectType: TT,
        objectId: u("userset_cond_userset_ch/10"),
        relation: "userset_cond_userset_ch",
        subjectType: USER,
        subjectId: u("userset_cond_userset_ch/valid"),
        context: { x: "1" },
        expected: true,
      },
      {
        name: "userset_cond_userset_ch/no_path_to_user_because_cond_is_false",
        objectType: TT,
        objectId: u("userset_cond_userset_ch/10"),
        relation: "userset_cond_userset_ch",
        subjectType: USER,
        subjectId: u("userset_cond_userset_ch/valid"),
        context: { x: "2" },
        expected: false,
      },
      {
        name: "userset_cond_userset_ch/path_to_employee_and_cond_is_true",
        objectType: TT,
        objectId: u("userset_cond_userset_ch/10"),
        relation: "userset_cond_userset_ch",
        subjectType: EMPLOYEE,
        subjectId: u("userset_cond_userset_ch/valid"),
        context: { x: "1" },
        expected: true,
      },
      {
        name: "userset_cond_userset_ch/no_path_to_employee_because_cond_is_false",
        objectType: TT,
        objectId: u("userset_cond_userset_ch/10"),
        relation: "userset_cond_userset_ch",
        subjectType: EMPLOYEE,
        subjectId: u("userset_cond_userset_ch/valid"),
        context: { x: "2" },
        expected: false,
      },
      {
        name: "userset_cond_userset_ch/no_path_to_user_because_user_not_in_userset",
        objectType: TT,
        objectId: u("userset_cond_userset_ch/10_disconnected_1"),
        relation: "userset_cond_userset_ch",
        subjectType: USER,
        subjectId: u("userset_cond_userset_ch/valid"),
        context: { x: "1" },
        expected: false,
      },
      {
        name: "userset_cond_userset_ch/no_path_to_user_because_parent_not_linked_to_object",
        objectType: TT,
        objectId: u("userset_cond_userset_ch/10_disconnected_2"),
        relation: "userset_cond_userset_ch",
        subjectType: USER,
        subjectId: u("userset_cond_userset_ch/valid"),
        context: { x: "1" },
        expected: false,
      },
    ],
  },
  {
    name: "userset_cond_userset_comp_ch",
    tuples: [
      {
        objectType: TT,
        objectId: u("userset_cond_userset_comp_ch/11"),
        relation: "userset_cond_parent",
        subjectType: UU,
        subjectId: u("userset_cond_userset_comp_ch/ttu_11"),
        conditionName: XCOND,
      },
      {
        objectType: UU,
        objectId: u("userset_cond_userset_comp_ch/ttu_11"),
        relation: "userset_to_computed",
        subjectType: DU,
        subjectId: u("userset_cond_userset_comp_ch/ttu_11"),
        subjectRelation: "computed",
      },
      {
        objectType: DU,
        objectId: u("userset_cond_userset_comp_ch/ttu_11"),
        relation: "direct",
        subjectType: USER,
        subjectId: u("userset_cond_userset_comp_ch/valid"),
      },
      {
        objectType: UU,
        objectId: u("userset_cond_userset_comp_ch/ttu_11"),
        relation: "userset_to_computed",
        subjectType: DE,
        subjectId: u("userset_cond_userset_comp_ch/ttu_11"),
        subjectRelation: "computed",
      },
      {
        objectType: DE,
        objectId: u("userset_cond_userset_comp_ch/ttu_11"),
        relation: "direct",
        subjectType: EMPLOYEE,
        subjectId: u("userset_cond_userset_comp_ch/valid"),
      },
      {
        objectType: TT,
        objectId: u("userset_cond_userset_comp_ch/11_disconnected_1"),
        relation: "userset_cond_parent",
        subjectType: UU,
        subjectId: u("userset_cond_userset_comp_ch/ttu_11_disconnected_1"),
        conditionName: XCOND,
      },
      {
        objectType: UU,
        objectId: u("userset_cond_userset_comp_ch/ttu_11_disconnected_1"),
        relation: "userset_to_computed",
        subjectType: DU,
        subjectId: u("userset_cond_userset_comp_ch/11_disconnected"),
        subjectRelation: "computed",
      },
      {
        objectType: TT,
        objectId: u("userset_cond_userset_comp_ch/11_disconnected_2"),
        relation: "userset_cond_parent",
        subjectType: UU,
        subjectId: u("userset_cond_userset_comp_ch/ttu_11_disconnected_2"),
        conditionName: XCOND,
      },
    ],
    cases: [
      {
        name: "userset_cond_userset_comp_ch/path_to_user_and_cond_is_true",
        objectType: TT,
        objectId: u("userset_cond_userset_comp_ch/11"),
        relation: "userset_cond_userset_comp_ch",
        subjectType: USER,
        subjectId: u("userset_cond_userset_comp_ch/valid"),
        context: { x: "1" },
        expected: true,
      },
      {
        name: "userset_cond_userset_comp_ch/no_path_to_user_because_cond_is_false",
        objectType: TT,
        objectId: u("userset_cond_userset_comp_ch/11"),
        relation: "userset_cond_userset_comp_ch",
        subjectType: USER,
        subjectId: u("userset_cond_userset_comp_ch/valid"),
        context: { x: "2" },
        expected: false,
      },
      {
        name: "userset_cond_userset_comp_ch/path_to_employee_and_cond_is_true",
        objectType: TT,
        objectId: u("userset_cond_userset_comp_ch/11"),
        relation: "userset_cond_userset_comp_ch",
        subjectType: EMPLOYEE,
        subjectId: u("userset_cond_userset_comp_ch/valid"),
        context: { x: "1" },
        expected: true,
      },
      {
        name: "userset_cond_userset_comp_ch/no_path_to_employee_because_cond_is_false",
        objectType: TT,
        objectId: u("userset_cond_userset_comp_ch/11"),
        relation: "userset_cond_userset_comp_ch",
        subjectType: EMPLOYEE,
        subjectId: u("userset_cond_userset_comp_ch/valid"),
        context: { x: "2" },
        expected: false,
      },
      {
        name: "userset_cond_userset_comp_ch/no_path_to_user_because_user_not_in_userset",
        objectType: TT,
        objectId: u("userset_cond_userset_comp_ch/11_disconnected_1"),
        relation: "userset_cond_userset_comp_ch",
        subjectType: USER,
        subjectId: u("userset_cond_userset_comp_ch/valid"),
        context: { x: "1" },
        expected: false,
      },
      {
        name: "userset_cond_userset_comp_ch/no_path_to_user_because_parent_not_linked_to_object",
        objectType: TT,
        objectId: u("userset_cond_userset_comp_ch/11_disconnected_2"),
        relation: "userset_cond_userset_comp_ch",
        subjectType: USER,
        subjectId: u("userset_cond_userset_comp_ch/valid"),
        context: { x: "1" },
        expected: false,
      },
    ],
  },
  {
    name: "userset_cond_userset_comp_cond_ch",
    tuples: [
      {
        objectType: TT,
        objectId: u("userset_cond_userset_comp_cond_ch/12"),
        relation: "userset_cond_parent",
        subjectType: UU,
        subjectId: u("userset_cond_userset_comp_cond_ch/ttu_12"),
        conditionName: XCOND,
      },
      {
        objectType: UU,
        objectId: u("userset_cond_userset_comp_cond_ch/ttu_12"),
        relation: "userset_to_computed_cond",
        subjectType: DU,
        subjectId: u("userset_cond_userset_comp_cond_ch/ttu_12"),
        subjectRelation: "computed_cond",
      },
      {
        objectType: DU,
        objectId: u("userset_cond_userset_comp_cond_ch/ttu_12"),
        relation: "direct_cond",
        subjectType: USER,
        subjectId: u("userset_cond_userset_comp_cond_ch/valid"),
        conditionName: XCOND,
      },
      {
        objectType: UU,
        objectId: u("userset_cond_userset_comp_cond_ch/ttu_12"),
        relation: "userset_to_computed_cond",
        subjectType: DE,
        subjectId: u("userset_cond_userset_comp_cond_ch/ttu_12"),
        subjectRelation: "direct_cond",
      },
      {
        objectType: DE,
        objectId: u("userset_cond_userset_comp_cond_ch/ttu_12"),
        relation: "direct_cond",
        subjectType: EMPLOYEE,
        subjectId: u("userset_cond_userset_comp_cond_ch/valid"),
        conditionName: XCOND,
      },
      {
        objectType: TT,
        objectId: u("userset_cond_userset_comp_cond_ch/12_disconnected"),
        relation: "userset_cond_parent",
        subjectType: UU,
        subjectId: u("userset_cond_userset_comp_cond_ch/ttu_12_disconnected"),
        conditionName: XCOND,
      },
      {
        objectType: UU,
        objectId: u("userset_cond_userset_comp_cond_ch/ttu_12_udisconnected"),
        relation: "userset_to_computed_cond",
        subjectType: DU,
        subjectId: u("userset_cond_userset_comp_cond_ch/ttu_12_disconnected"),
        subjectRelation: "computed_cond",
      },
    ],
    cases: [
      {
        name: "userset_cond_userset_comp_cond_ch/path_to_user_and_cond_is_true",
        objectType: TT,
        objectId: u("userset_cond_userset_comp_cond_ch/12"),
        relation: "userset_cond_userset_comp_cond_ch",
        subjectType: USER,
        subjectId: u("userset_cond_userset_comp_cond_ch/valid"),
        context: { x: "1" },
        expected: true,
      },
      {
        name: "userset_cond_userset_comp_cond_ch/no_path_to_user_because_cond_is_false",
        objectType: TT,
        objectId: u("userset_cond_userset_comp_cond_ch/12"),
        relation: "userset_cond_userset_comp_cond_ch",
        subjectType: USER,
        subjectId: u("userset_cond_userset_comp_cond_ch/valid"),
        context: { x: "2" },
        expected: false,
      },
      {
        name: "userset_cond_userset_comp_cond_ch/path_to_employee_and_cond_is_true",
        objectType: TT,
        objectId: u("userset_cond_userset_comp_cond_ch/12"),
        relation: "userset_cond_userset_comp_cond_ch",
        subjectType: EMPLOYEE,
        subjectId: u("userset_cond_userset_comp_cond_ch/valid"),
        context: { x: "1" },
        expected: true,
      },
      {
        name: "userset_cond_userset_comp_cond_ch/no_path_to_employee_because_cond_is_false",
        objectType: TT,
        objectId: u("userset_cond_userset_comp_cond_ch/12"),
        relation: "userset_cond_userset_comp_cond_ch",
        subjectType: EMPLOYEE,
        subjectId: u("userset_cond_userset_comp_cond_ch/valid"),
        context: { x: "2" },
        expected: false,
      },
      {
        name: "userset_cond_userset_comp_cond_ch/disconnected",
        objectType: TT,
        objectId: u("userset_cond_userset_comp_cond_ch/12_disconnected"),
        relation: "userset_cond_userset_comp_cond_ch",
        subjectType: USER,
        subjectId: u("userset_cond_userset_comp_cond_ch/valid"),
        context: { x: "1" },
        expected: false,
      },
    ],
  },
  {
    name: "userset_cond_userset_comp_wild_ch",
    tuples: [
      {
        objectType: TT,
        objectId: u("userset_cond_userset_comp_wild_ch/13"),
        relation: "userset_cond_parent",
        subjectType: UU,
        subjectId: u("userset_cond_userset_comp_wild_ch/ttu_13"),
        conditionName: XCOND,
      },
      {
        objectType: UU,
        objectId: u("userset_cond_userset_comp_wild_ch/ttu_13"),
        relation: "userset_to_computed_wild",
        subjectType: DU,
        subjectId: u("userset_cond_userset_comp_wild_ch/ttu_13"),
        subjectRelation: "computed_wild",
      },
      {
        objectType: DU,
        objectId: u("userset_cond_userset_comp_wild_ch/ttu_13"),
        relation: "direct_wild",
        subjectType: USER,
        subjectId: "*",
      },
      {
        objectType: UU,
        objectId: u("userset_cond_userset_comp_wild_ch/ttu_13"),
        relation: "userset_to_computed_wild",
        subjectType: DE,
        subjectId: u("userset_cond_userset_comp_wild_ch/ttu_13"),
        subjectRelation: "direct_wild",
      },
      {
        objectType: DE,
        objectId: u("userset_cond_userset_comp_wild_ch/ttu_13"),
        relation: "direct_wild",
        subjectType: EMPLOYEE,
        subjectId: "*",
      },
      {
        objectType: TT,
        objectId: u("userset_cond_userset_comp_wild_ch/13_unconnected"),
        relation: "userset_cond_parent",
        subjectType: UU,
        subjectId: u("userset_cond_userset_comp_wild_ch/ttu_13_unconnected"),
        conditionName: XCOND,
      },
      {
        objectType: UU,
        objectId: u("userset_cond_userset_comp_wild_ch/ttu_13_unconnected"),
        relation: "userset_to_computed_wild",
        subjectType: DU,
        subjectId: u("userset_cond_userset_comp_wild_ch/ttu_13_unconnected"),
        subjectRelation: "computed_wild",
      },
    ],
    cases: [
      {
        name: "userset_cond_userset_comp_wild_ch/path_to_random_user_and_cond_is_true",
        objectType: TT,
        objectId: u("userset_cond_userset_comp_wild_ch/13"),
        relation: "userset_cond_userset_comp_wild_ch",
        subjectType: USER,
        subjectId: u("userset_cond_userset_comp_wild_ch/1"),
        context: { x: "1" },
        expected: true,
      },
      {
        name: "userset_cond_userset_comp_wild_ch/path_to_another_random_user_and_cond_is_true",
        objectType: TT,
        objectId: u("userset_cond_userset_comp_wild_ch/13"),
        relation: "userset_cond_userset_comp_wild_ch",
        subjectType: USER,
        subjectId: u("userset_cond_userset_comp_wild_ch/2"),
        context: { x: "1" },
        expected: true,
      },
      {
        name: "userset_cond_userset_comp_wild_ch/no_path_to_random_user_because_cond_is_false",
        objectType: TT,
        objectId: u("userset_cond_userset_comp_wild_ch/13"),
        relation: "userset_cond_userset_comp_wild_ch",
        subjectType: USER,
        subjectId: u("userset_cond_userset_comp_wild_ch/1"),
        context: { x: "2" },
        expected: false,
      },
      {
        name: "userset_cond_userset_comp_wild_ch/no_path_to_another_random_user_because_cond_is_false",
        objectType: TT,
        objectId: u("userset_cond_userset_comp_wild_ch/13"),
        relation: "userset_cond_userset_comp_wild_ch",
        subjectType: USER,
        subjectId: u("userset_cond_userset_comp_wild_ch/2"),
        context: { x: "2" },
        expected: false,
      },
      {
        name: "userset_cond_userset_comp_wild_ch/path_to_random_employee_and_cond_is_true",
        objectType: TT,
        objectId: u("userset_cond_userset_comp_wild_ch/13"),
        relation: "userset_cond_userset_comp_wild_ch",
        subjectType: EMPLOYEE,
        subjectId: u("userset_cond_userset_comp_wild_ch/1"),
        context: { x: "1" },
        expected: true,
      },
      {
        name: "userset_cond_userset_comp_wild_ch/path_to_another_random_employee_and_cond_is_true",
        objectType: TT,
        objectId: u("userset_cond_userset_comp_wild_ch/13"),
        relation: "userset_cond_userset_comp_wild_ch",
        subjectType: EMPLOYEE,
        subjectId: u("userset_cond_userset_comp_wild_ch/2"),
        context: { x: "1" },
        expected: true,
      },
      {
        name: "userset_cond_userset_comp_wild_ch/unconnected_from_wildcard_even_if_cond_is_true",
        objectType: TT,
        objectId: u("userset_cond_userset_comp_wild_ch/13_unconnected"),
        relation: "userset_cond_userset_comp_wild_ch",
        subjectType: USER,
        subjectId: u("userset_cond_userset_comp_wild_ch/1"),
        context: { x: "1" },
        expected: false,
      },
    ],
  },
  {
    name: "userset_cond_userset_comp_wild_cond_ch",
    tuples: [
      {
        objectType: TT,
        objectId: u("userset_cond_userset_comp_wild_cond_ch/14"),
        relation: "userset_cond_parent",
        subjectType: UU,
        subjectId: u("userset_cond_userset_comp_wild_cond_ch/ttu_14"),
        conditionName: XCOND,
      },
      {
        objectType: UU,
        objectId: u("userset_cond_userset_comp_wild_cond_ch/ttu_14"),
        relation: "userset_to_computed_wild_cond",
        subjectType: DU,
        subjectId: u("userset_cond_userset_comp_wild_cond_ch/ttu_14"),
        subjectRelation: "direct_wild_cond",
      },
      {
        objectType: DU,
        objectId: u("userset_cond_userset_comp_wild_cond_ch/ttu_14"),
        relation: "direct_wild_cond",
        subjectType: USER,
        subjectId: "*",
        conditionName: XCOND,
      },
      {
        objectType: TT,
        objectId: u("userset_cond_userset_comp_wild_cond_ch/14_unconnected"),
        relation: "userset_cond_parent",
        subjectType: UU,
        subjectId: u(
          "userset_cond_userset_comp_wild_cond_ch/ttu_14_unconnected",
        ),
        conditionName: XCOND,
      },
    ],
    cases: [
      {
        name: "userset_cond_userset_comp_wild_cond_ch/missing_context_for_condition",
        objectType: TT,
        objectId: u("userset_cond_userset_comp_wild_cond_ch/14"),
        relation: "userset_cond_userset_comp_wild_cond_ch",
        subjectType: USER,
        subjectId: u("userset_cond_userset_comp_wild_cond_ch/1"),
        expected: "refused",
      },
      {
        name: "userset_cond_userset_comp_wild_cond_ch/path_and_cond_true",
        objectType: TT,
        objectId: u("userset_cond_userset_comp_wild_cond_ch/14"),
        relation: "userset_cond_userset_comp_wild_cond_ch",
        subjectType: USER,
        subjectId: u("userset_cond_userset_comp_wild_cond_ch/1"),
        context: { x: "1" },
        expected: true,
      },
      {
        name: "userset_cond_userset_comp_wild_cond_ch/path_for_diff_user_and_cond_true",
        objectType: TT,
        objectId: u("userset_cond_userset_comp_wild_cond_ch/14"),
        relation: "userset_cond_userset_comp_wild_cond_ch",
        subjectType: USER,
        subjectId: u("userset_cond_userset_comp_wild_cond_ch/2"),
        context: { x: "1" },
        expected: true,
      },
      {
        name: "userset_cond_userset_comp_wild_cond_ch/path_but_cond_false",
        objectType: TT,
        objectId: u("userset_cond_userset_comp_wild_cond_ch/14"),
        relation: "userset_cond_userset_comp_wild_cond_ch",
        subjectType: USER,
        subjectId: u("userset_cond_userset_comp_wild_cond_ch/1"),
        context: { x: "2" },
        expected: false,
      },
      {
        name: "userset_cond_userset_comp_wild_cond_ch/unconnected",
        objectType: TT,
        objectId: u("userset_cond_userset_comp_wild_cond_ch/14_unconnected"),
        relation: "userset_cond_userset_comp_wild_cond_ch",
        subjectType: USER,
        subjectId: u("userset_cond_userset_comp_wild_cond_ch/1"),
        context: { x: "1" },
        expected: false,
      },
    ],
  },
  {
    name: "or_ttu",
    tuples: [
      {
        objectType: TT,
        objectId: u("or_ttu/15_path_1"),
        relation: "mult_parent_types",
        subjectType: DU,
        subjectId: u("or_ttu/ttu_15_path_1"),
      },
      {
        objectType: DU,
        objectId: u("or_ttu/ttu_15_path_1"),
        relation: "direct",
        subjectType: USER,
        subjectId: u("or_ttu/valid_path_1"),
      },
      {
        objectType: TT,
        objectId: u("or_ttu/15_path_2"),
        relation: "mult_parent_types_cond",
        subjectType: DU,
        subjectId: u("or_ttu/ttu_15_path_2"),
        conditionName: XCOND,
      },
      {
        objectType: DU,
        objectId: u("or_ttu/ttu_15_path_2"),
        relation: "direct",
        subjectType: USER,
        subjectId: u("or_ttu/valid_path_2"),
      },
      {
        objectType: TT,
        objectId: u("or_ttu/15_path_both"),
        relation: "mult_parent_types",
        subjectType: DU,
        subjectId: u("or_ttu/ttu_15_path_both_1"),
      },
      {
        objectType: TT,
        objectId: u("or_ttu/15_path_both"),
        relation: "mult_parent_types_cond",
        subjectType: DU,
        subjectId: u("or_ttu/15_path_both_1"),
        conditionName: XCOND,
      },
      {
        objectType: DU,
        objectId: u("or_ttu/ttu_15_path_both_1"),
        relation: "direct",
        subjectType: USER,
        subjectId: u("or_ttu/valid_both"),
      },
      {
        objectType: DU,
        objectId: u("or_ttu/15_path_both_1"),
        relation: "direct",
        subjectType: USER,
        subjectId: u("or_ttu/valid_both"),
      },
    ],
    cases: [
      {
        name: "or_ttu/valid_path_1",
        objectType: TT,
        objectId: u("or_ttu/15_path_1"),
        relation: "or_ttu",
        subjectType: USER,
        subjectId: u("or_ttu/valid_path_1"),
        expected: true,
      },
      {
        name: "or_ttu/valid_path_2",
        objectType: TT,
        objectId: u("or_ttu/15_path_2"),
        relation: "or_ttu",
        subjectType: USER,
        subjectId: u("or_ttu/valid_path_2"),
        context: { x: "1" },
        expected: true,
      },
      {
        name: "or_ttu/valid_path_2_but_cond_is_false",
        objectType: TT,
        objectId: u("or_ttu/15_path_2"),
        relation: "or_ttu",
        subjectType: USER,
        subjectId: u("or_ttu/valid_path_2"),
        context: { x: "2" },
        expected: false,
      },
      {
        name: "or_ttu/valid_both",
        objectType: TT,
        objectId: u("or_ttu/15_path_both"),
        relation: "or_ttu",
        subjectType: USER,
        subjectId: u("or_ttu/valid_both"),
        context: { x: "1" },
        expected: true,
      },
    ],
  },
  {
    name: "and_ttu",
    tuples: [
      {
        objectType: TT,
        objectId: u("and_ttu/16_path_1"),
        relation: "direct_parent",
        subjectType: DU,
        subjectId: u("and_ttu/ttu_16_parent_path_1"),
      },
      {
        objectType: DU,
        objectId: u("and_ttu/ttu_16_parent_path_1"),
        relation: "direct_wild",
        subjectType: USER,
        subjectId: "*",
      },
      {
        objectType: TT,
        objectId: u("and_ttu/16_path_1"),
        relation: "mult_parent_types",
        subjectType: DU,
        subjectId: u("and_ttu/ttu_16_parent_path_12"),
      },
      {
        objectType: DU,
        objectId: u("and_ttu/ttu_16_parent_path_12"),
        relation: "direct",
        subjectType: USER,
        subjectId: u("and_ttu/valid1"),
      },
      {
        objectType: TT,
        objectId: u("and_ttu/16_path_2"),
        relation: "direct_parent",
        subjectType: DU,
        subjectId: u("and_ttu/ttu_16_parent_path_2"),
      },
      {
        objectType: DU,
        objectId: u("and_ttu/ttu_16_parent_path_2"),
        relation: "direct",
        subjectType: USER,
        subjectId: u("and_ttu/valid2"),
      },
      {
        objectType: TT,
        objectId: u("and_ttu/16_path_2"),
        relation: "mult_parent_types",
        subjectType: DU,
        subjectId: u("and_ttu/ttu_16_parent_path_22"),
      },
      {
        objectType: DU,
        objectId: u("and_ttu/ttu_16_parent_path_22"),
        relation: "direct",
        subjectType: USER,
        subjectId: u("and_ttu/valid2"),
      },
      {
        objectType: TT,
        objectId: u("and_ttu/16_path_3"),
        relation: "direct_parent",
        subjectType: DU,
        subjectId: u("and_ttu/ttu_16_parent_path_3"),
      },
      {
        objectType: DU,
        objectId: u("and_ttu/ttu_16_parent_path_3"),
        relation: "direct_cond",
        subjectType: USER,
        subjectId: u("and_ttu/valid3"),
        conditionName: XCOND,
      },
      {
        objectType: TT,
        objectId: u("and_ttu/16_path_3"),
        relation: "mult_parent_types",
        subjectType: DU,
        subjectId: u("and_ttu/ttu_16_parent_path_32"),
      },
      {
        objectType: DU,
        objectId: u("and_ttu/ttu_16_parent_path_32"),
        relation: "direct",
        subjectType: USER,
        subjectId: u("and_ttu/valid3"),
      },
    ],
    cases: [
      {
        name: "and_ttu/valid_path_1",
        objectType: TT,
        objectId: u("and_ttu/16_path_1"),
        relation: "and_ttu",
        subjectType: USER,
        subjectId: u("and_ttu/valid1"),
        expected: true,
      },
      {
        name: "and_ttu/no_path_1",
        objectType: TT,
        objectId: u("and_ttu/16_path_1"),
        relation: "and_ttu",
        subjectType: USER,
        subjectId: u("and_ttu/valid2"),
        expected: false,
      },
      {
        name: "and_ttu/valid_path_2",
        objectType: TT,
        objectId: u("and_ttu/16_path_2"),
        relation: "and_ttu",
        subjectType: USER,
        subjectId: u("and_ttu/valid2"),
        expected: true,
      },
      {
        name: "and_ttu/no_path_2",
        objectType: TT,
        objectId: u("and_ttu/16_path_2"),
        relation: "and_ttu",
        subjectType: USER,
        subjectId: u("and_ttu/valid1"),
        expected: false,
      },
      {
        name: "and_ttu/valid_path_3",
        objectType: TT,
        objectId: u("and_ttu/16_path_3"),
        relation: "and_ttu",
        subjectType: USER,
        subjectId: u("and_ttu/valid3"),
        context: { x: "1" },
        expected: true,
      },
      {
        name: "and_ttu/no_path_3_because_condition_missing",
        objectType: TT,
        objectId: u("and_ttu/16_path_3"),
        relation: "and_ttu",
        subjectType: USER,
        subjectId: u("and_ttu/valid3"),
        context: { x: "2" },
        expected: false,
      },
    ],
  },
  {
    name: "nested_butnot_ttu",
    tuples: [
      {
        objectType: TT,
        objectId: u("nested_butnot_ttu/17"),
        relation: "direct_parent",
        subjectType: DU,
        subjectId: u("nested_butnot_ttu/ttu_17"),
      },
      {
        objectType: DU,
        objectId: u("nested_butnot_ttu/ttu_17"),
        relation: "direct",
        subjectType: USER,
        subjectId: u("nested_butnot_ttu/1"),
      },
      {
        objectType: TT,
        objectId: u("nested_butnot_ttu/17"),
        relation: "userset_parent",
        subjectType: UU,
        subjectId: u("nested_butnot_ttu/ttu_17"),
      },
      {
        objectType: UU,
        objectId: u("nested_butnot_ttu/ttu_17"),
        relation: "userset_to_computed_wild",
        subjectType: DU,
        subjectId: u("nested_butnot_ttu/ttu_17"),
        subjectRelation: "computed_wild",
      },
      {
        objectType: DU,
        objectId: u("nested_butnot_ttu/ttu_17"),
        relation: "direct_wild",
        subjectType: USER,
        subjectId: "*",
      },
      {
        objectType: TT,
        objectId: u("nested_butnot_ttu/17_1"),
        relation: "direct_parent",
        subjectType: DU,
        subjectId: u("nested_butnot_ttu/ttu_17_1"),
      },
      {
        objectType: DU,
        objectId: u("nested_butnot_ttu/ttu_17_1"),
        relation: "direct",
        subjectType: USER,
        subjectId: u("nested_butnot_ttu/1"),
      },
      {
        objectType: TT,
        objectId: u("nested_butnot_ttu/17_1"),
        relation: "userset_parent",
        subjectType: UU,
        subjectId: u("nested_butnot_ttu/ttu_17_1"),
      },
      {
        objectType: UU,
        objectId: u("nested_butnot_ttu/ttu_17_1"),
        relation: "userset_to_computed_wild",
        subjectType: DE,
        subjectId: u("nested_butnot_ttu/ttu_17_1"),
        subjectRelation: "direct_wild",
      },
      {
        objectType: DE,
        objectId: u("nested_butnot_ttu/ttu_17_1"),
        relation: "direct_wild",
        subjectType: EMPLOYEE,
        subjectId: "*",
      },
    ],
    cases: [
      {
        name: "nested_butnot_ttu/base_true_diff_true",
        objectType: TT,
        objectId: u("nested_butnot_ttu/17"),
        relation: "nested_butnot_ttu",
        subjectType: USER,
        subjectId: u("nested_butnot_ttu/1"),
        expected: false,
      },
      {
        name: "nested_butnot_ttu/base_false_diff_true",
        objectType: TT,
        objectId: u("nested_butnot_ttu/17"),
        relation: "nested_butnot_ttu",
        subjectType: USER,
        subjectId: u("nested_butnot_ttu/2"),
        expected: false,
      },
      {
        name: "nested_butnot_ttu/base_true_diff_false",
        objectType: TT,
        objectId: u("nested_butnot_ttu/17_1"),
        relation: "nested_butnot_ttu",
        subjectType: USER,
        subjectId: u("nested_butnot_ttu/1"),
        expected: true,
      },
      {
        name: "nested_butnot_ttu/base_false_diff_false",
        objectType: TT,
        objectId: u("nested_butnot_ttu/17_1"),
        relation: "nested_butnot_ttu",
        subjectType: USER,
        subjectId: u("nested_butnot_ttu/2"),
        expected: false,
      },
    ],
  },
];

describe("B1 tuple-to-userset corpus — parents, conditions, algebra", () => {
  let db: Kysely<DB>;
  let corpus: Corpus;
  let fixture: FixtureRecord;

  beforeAll(async () => {
    db = getDb();
    await beginTransaction(db);

    const tsfgaClient = createTsfga(new KyselyTupleStore(db));
    fixture = recordFixture(tsfgaClient);
    corpus = await loadCorpus(tsfgaClient, {
      slug: "ttu-matrix",
      modelPath: "./ttu-matrix/model.dsl",
      conditions: [
        {
          name: XCOND,
          expression: "x == '1'",
          parameters: { x: "string" },
        },
      ],
      configs: CONFIGS,
      stages: STAGES,
    });
  });

  afterAll(async () => {
    await rollbackTransaction(db);
    await destroyDb();
  });

  runStages(STAGES, () => corpus);

  test("the configs say what the model says", () => {
    expectConfigsMatchModel("./ttu-matrix/model.dsl", fixture, {
      coverage: "complete",
    });
  });
});
