/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface TsfgaConditionDefinitions {
  expression: string;
  id: Generated<Int8>;
  name: string;
  parameters: Json | null;
}

export interface TsfgaRelationConfigs {
  computed_userset: string | null;
  directly_assignable: Json;
  excluded_by: string | null;
  id: Generated<Int8>;
  implied_by: string[] | null;
  intersection: Json | null;
  object_type: string;
  relation: string;
  tuple_to_userset: Json | null;
}

export interface TsfgaTuples {
  condition_context: Json | null;
  condition_name: string | null;
  created_at: Timestamp;
  id: Generated<Int8>;
  object_id: string;
  object_type: string;
  relation: string;
  subject_id: string | null;
  subject_relation: string | null;
  subject_type: string;
  subject_wildcard: boolean;
  updated_at: Timestamp;
}

export interface DB {
  "tsfga.condition_definitions": TsfgaConditionDefinitions;
  "tsfga.relation_configs": TsfgaRelationConfigs;
  "tsfga.tuples": TsfgaTuples;
}
